### ISSUE TITLE
Issues running `mintNtfsToCollection` 

### ISSUE THREAD

**Issue by beeman** [wen-community/wns-sample-mint#3]
I tried to run the example script and after adding some deps (see #2) I'm running into an error.

When I invoke the `initializeCollection` endpoint it works and I get back a collection ID. However, when I go ahead and invoke `mintNftsToCollection` passing in the collection ID, I get an error message:

```shell
❯ curl -XPOST localhost/initializeCollection
AcMj8wEt9qza8uMUU6SbJz1YQWf2q9xTtVqrkynFKD4g
❯ curl -XPOST localhost/mintNftsToCollection  -H 'content-type: application/json' --data '{ "collection":"AcMj8wEt9qza8uMUU6SbJz1YQWf2q9xTtVqrkynFKD4g" }'
curl: (52) Empty reply from server
```

This is the error I'm getting:
```
yarn run v1.22.19
$ ts-node src/index.ts
The application is listening on port 80!
{ distribution: '52jAC9aRsE9jVdvqtqdDeeTVqHYmvMF9yvHr9eosrtiB' }
/Users/beeman/dev/github/wen-community/wns-sample-mint/node_modules/@solana/web3.js/src/connection.ts:5921
      throw new SendTransactionError(
            ^
SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 1: invalid program argument
    at Connection.sendEncodedTransaction (/Users/beeman/dev/github/wen-community/wns-sample-mint/node_modules/@solana/web3.js/src/connection.ts:5921:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Connection.sendRawTransaction (/Users/beeman/dev/github/wen-community/wns-sample-mint/node_modules/@solana/web3.js/src/connection.ts:5880:20)
    at async Connection.sendTransaction (/Users/beeman/dev/github/wen-community/wns-sample-mint/node_modules/@solana/web3.js/src/connection.ts:5829:14) {
  logs: [
    'Program ComputeBudget111111111111111111111111111111 invoke [1]',
    'Program ComputeBudget111111111111111111111111111111 success',
    'Program wns1gDLt8fgLcGhWi5MqAqgXpwEP1JftKE9eZnXS1HM invoke [1]',
    'Program log: Instruction: CreateMintAccount',
    'Program 11111111111111111111111111111111 invoke [2]',
    'Program 11111111111111111111111111111111 success',
    'Program TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb invoke [2]',
    'Program log: GroupMemberPointerInstruction::Initialize',
    'Program TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb consumed 2439 of 586370 compute units',
    'Program TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb success',
    'Program TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb invoke [2]',
    'Program log: MetadataPointerInstruction::Initialize',
    'Program TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb consumed 2508 of 580984 compute units',
    'Program TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb success',
    'Program TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb invoke [2]',
    'Program log: Instruction: InitializeMintCloseAuthority',
    'Program TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb consumed 2630 of 576087 compute units',
    'Program TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb success',
    'Program TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb invoke [2]',
    'Program log: TransferHookInstruction::Initialize',
    'Program TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb consumed 2705 of 570583 compute units',
    'Program TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb success',
    'Program TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb invoke [2]',
    'Program log: Instruction: InitializePermanentDelegate',
    'Program log: Error: InvalidArgument',
    'Program TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb consumed 2782 of 565478 compute units',
    'Program TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb failed: invalid program argument',
    'Program wns1gDLt8fgLcGhWi5MqAqgXpwEP1JftKE9eZnXS1HM consumed 37154 of 599850 compute units',
    'Program wns1gDLt8fgLcGhWi5MqAqgXpwEP1JftKE9eZnXS1HM failed: invalid program argument'
  ]
}
```

**Comment by balmy-gazebo** [comment]
Delegate looks to be passed in wrong, pushing a fix now
